/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as PressRouteImport } from './routes/press'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as WhereToSeeRouteImport } from './routes/where-to-see'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const WhereToSeeRoute = WhereToSeeRouteImport.update({
  id: '/where-to-see',
  path: '/where-to-see',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/press': typeof PressRoute
  '/shop': typeof ShopRoute
  '/studio': typeof StudioRoute
  '/where-to-see': typeof WhereToSeeRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/news/': typeof NewsIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/press': typeof PressRoute
  '/shop': typeof ShopRoute
  '/studio': typeof StudioRoute
  '/where-to-see': typeof WhereToSeeRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/news': typeof NewsIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/press': typeof PressRoute
  '/shop': typeof ShopRoute
  '/studio': typeof StudioRoute
  '/where-to-see': typeof WhereToSeeRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/news/': typeof NewsIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/press'
    | '/shop'
    | '/studio'
    | '/where-to-see'
    | '/checkout/return'
    | '/news/'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/press'
    | '/shop'
    | '/studio'
    | '/where-to-see'
    | '/checkout/return'
    | '/news'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/press'
    | '/shop'
    | '/studio'
    | '/where-to-see'
    | '/checkout/return'
    | '/news/'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  PressRoute: typeof PressRoute
  ShopRoute: typeof ShopRoute
  StudioRoute: typeof StudioRoute
  WhereToSeeRoute: typeof WhereToSeeRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  NewsIndexRoute: typeof NewsIndexRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/where-to-see': {
      id: '/where-to-see'
      path: '/where-to-see'
      fullPath: '/where-to-see'
      preLoaderRoute: typeof WhereToSeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  PressRoute: PressRoute,
  ShopRoute: ShopRoute,
  StudioRoute: StudioRoute,
  WhereToSeeRoute: WhereToSeeRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  NewsIndexRoute: NewsIndexRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
