/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CommissionsRouteImport } from './routes/commissions'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PressRouteImport } from './routes/press'
import { Route as RsvpRouteImport } from './routes/rsvp'
import { Route as RsvpSalonRouteImport } from './routes/rsvp-salon'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as WhereToSeeRouteImport } from './routes/where-to-see'
import { Route as AuthenticatedArtworkAdminRouteImport } from './routes/_authenticated/artwork-admin'
import { Route as AuthenticatedNewsAdminRouteImport } from './routes/_authenticated/news-admin'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as GalleryIndexRouteImport } from './routes/gallery.index'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as ApiPublicArtworkImageRouteImport } from './routes/api/public/artwork-image'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CommissionsRoute = CommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const RsvpRoute = RsvpRouteImport.update({
  id: '/rsvp',
  path: '/rsvp',
  getParentRoute: () => rootRouteImport,
} as any)
const RsvpSalonRoute = RsvpSalonRouteImport.update({
  id: '/rsvp-salon',
  path: '/rsvp-salon',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const WhereToSeeRoute = WhereToSeeRouteImport.update({
  id: '/where-to-see',
  path: '/where-to-see',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedArtworkAdminRoute =
  AuthenticatedArtworkAdminRouteImport.update({
    id: '/artwork-admin',
    path: '/artwork-admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNewsAdminRoute = AuthenticatedNewsAdminRouteImport.update({
  id: '/news-admin',
  path: '/news-admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryIndexRoute = GalleryIndexRouteImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicArtworkImageRoute = ApiPublicArtworkImageRouteImport.update({
  id: '/api/public/artwork-image',
  path: '/api/public/artwork-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/commissions': typeof CommissionsRoute
  '/contact': typeof ContactRoute
  '/press': typeof PressRoute
  '/rsvp': typeof RsvpRoute
  '/rsvp-salon': typeof RsvpSalonRoute
  '/shop': typeof ShopRoute
  '/studio': typeof StudioRoute
  '/where-to-see': typeof WhereToSeeRoute
  '/artwork-admin': typeof AuthenticatedArtworkAdminRoute
  '/news-admin': typeof AuthenticatedNewsAdminRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/news/$slug': typeof NewsSlugRoute
  '/gallery/': typeof GalleryIndexRoute
  '/news/': typeof NewsIndexRoute
  '/api/public/artwork-image': typeof ApiPublicArtworkImageRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/commissions': typeof CommissionsRoute
  '/contact': typeof ContactRoute
  '/press': typeof PressRoute
  '/rsvp': typeof RsvpRoute
  '/rsvp-salon': typeof RsvpSalonRoute
  '/shop': typeof ShopRoute
  '/studio': typeof StudioRoute
  '/where-to-see': typeof WhereToSeeRoute
  '/artwork-admin': typeof AuthenticatedArtworkAdminRoute
  '/news-admin': typeof AuthenticatedNewsAdminRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/news/$slug': typeof NewsSlugRoute
  '/gallery': typeof GalleryIndexRoute
  '/news': typeof NewsIndexRoute
  '/api/public/artwork-image': typeof ApiPublicArtworkImageRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/commissions': typeof CommissionsRoute
  '/contact': typeof ContactRoute
  '/press': typeof PressRoute
  '/rsvp': typeof RsvpRoute
  '/rsvp-salon': typeof RsvpSalonRoute
  '/shop': typeof ShopRoute
  '/studio': typeof StudioRoute
  '/where-to-see': typeof WhereToSeeRoute
  '/_authenticated/artwork-admin': typeof AuthenticatedArtworkAdminRoute
  '/_authenticated/news-admin': typeof AuthenticatedNewsAdminRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/news/$slug': typeof NewsSlugRoute
  '/gallery/': typeof GalleryIndexRoute
  '/news/': typeof NewsIndexRoute
  '/api/public/artwork-image': typeof ApiPublicArtworkImageRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/commissions'
    | '/contact'
    | '/press'
    | '/rsvp'
    | '/rsvp-salon'
    | '/shop'
    | '/studio'
    | '/where-to-see'
    | '/artwork-admin'
    | '/news-admin'
    | '/checkout/return'
    | '/news/$slug'
    | '/gallery/'
    | '/news/'
    | '/api/public/artwork-image'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/commissions'
    | '/contact'
    | '/press'
    | '/rsvp'
    | '/rsvp-salon'
    | '/shop'
    | '/studio'
    | '/where-to-see'
    | '/artwork-admin'
    | '/news-admin'
    | '/checkout/return'
    | '/news/$slug'
    | '/gallery'
    | '/news'
    | '/api/public/artwork-image'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/commissions'
    | '/contact'
    | '/press'
    | '/rsvp'
    | '/rsvp-salon'
    | '/shop'
    | '/studio'
    | '/where-to-see'
    | '/_authenticated/artwork-admin'
    | '/_authenticated/news-admin'
    | '/checkout/return'
    | '/news/$slug'
    | '/gallery/'
    | '/news/'
    | '/api/public/artwork-image'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CommissionsRoute: typeof CommissionsRoute
  ContactRoute: typeof ContactRoute
  PressRoute: typeof PressRoute
  RsvpRoute: typeof RsvpRoute
  RsvpSalonRoute: typeof RsvpSalonRoute
  ShopRoute: typeof ShopRoute
  StudioRoute: typeof StudioRoute
  WhereToSeeRoute: typeof WhereToSeeRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  NewsSlugRoute: typeof NewsSlugRoute
  GalleryIndexRoute: typeof GalleryIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  ApiPublicArtworkImageRoute: typeof ApiPublicArtworkImageRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commissions': {
      id: '/commissions'
      path: '/commissions'
      fullPath: '/commissions'
      preLoaderRoute: typeof CommissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rsvp': {
      id: '/rsvp'
      path: '/rsvp'
      fullPath: '/rsvp'
      preLoaderRoute: typeof RsvpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rsvp-salon': {
      id: '/rsvp-salon'
      path: '/rsvp-salon'
      fullPath: '/rsvp-salon'
      preLoaderRoute: typeof RsvpSalonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/where-to-see': {
      id: '/where-to-see'
      path: '/where-to-see'
      fullPath: '/where-to-see'
      preLoaderRoute: typeof WhereToSeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/artwork-admin': {
      id: '/_authenticated/artwork-admin'
      path: '/artwork-admin'
      fullPath: '/artwork-admin'
      preLoaderRoute: typeof AuthenticatedArtworkAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/news-admin': {
      id: '/_authenticated/news-admin'
      path: '/news-admin'
      fullPath: '/news-admin'
      preLoaderRoute: typeof AuthenticatedNewsAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/': {
      id: '/gallery/'
      path: '/gallery'
      fullPath: '/gallery/'
      preLoaderRoute: typeof GalleryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/artwork-image': {
      id: '/api/public/artwork-image'
      path: '/api/public/artwork-image'
      fullPath: '/api/public/artwork-image'
      preLoaderRoute: typeof ApiPublicArtworkImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedArtworkAdminRoute: typeof AuthenticatedArtworkAdminRoute
  AuthenticatedNewsAdminRoute: typeof AuthenticatedNewsAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedArtworkAdminRoute: AuthenticatedArtworkAdminRoute,
  AuthenticatedNewsAdminRoute: AuthenticatedNewsAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CommissionsRoute: CommissionsRoute,
  ContactRoute: ContactRoute,
  PressRoute: PressRoute,
  RsvpRoute: RsvpRoute,
  RsvpSalonRoute: RsvpSalonRoute,
  ShopRoute: ShopRoute,
  StudioRoute: StudioRoute,
  WhereToSeeRoute: WhereToSeeRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  NewsSlugRoute: NewsSlugRoute,
  GalleryIndexRoute: GalleryIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  ApiPublicArtworkImageRoute: ApiPublicArtworkImageRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
