INSERT INTO public.artworks (slug, title, year, medium, dimensions, description, image_url, original_available, original_price_cents, stripe_price_key, sort_order) VALUES
('adeline', 'Adeline', NULL, 'Oil', '15 × 12 × 1 in', NULL, '/artworks/img-3689/01-main.jpeg', false, NULL, NULL, 1000),
('all-the-good-things', 'All the Good Things', NULL, 'Oil', '16 × 24 × 1 in', NULL, '/artworks/img-3689/01-main.jpeg', false, NULL, NULL, 1001),
('anna', 'Anna', NULL, 'oil', '14 × 17 × 1 in', 'This piece is part of a series of paintings that integrate figurative work with a quilt, speaking to the threads of our personal history on relationship to others.', '/artworks/img-3689/01-main.jpeg', false, NULL, NULL, 1002),
('blue-boots', 'Blue boots', NULL, 'Oil', '20 × 16 × 1 in', NULL, '/artworks/img-3689/01-main.jpeg', false, NULL, NULL, 1003),
('brown-boots', 'Brown boots', NULL, NULL, NULL, NULL, '/artworks/img-3689/01-main.jpeg', false, NULL, NULL, 1004),
('celebration', 'Celebration', NULL, 'Digital, oil and embroidery', '24 × 18 × 2 in', NULL, '/artworks/img-3689/01-main.jpeg', false, NULL, NULL, 1005),
('chair-studies-three-panels', 'Chair studies (three panels)', NULL, NULL, NULL, NULL, '/artworks/seated-woman-in-pink-and-grey-installed-view/01-main.jpg', false, NULL, NULL, 1006),
('charcoal-figure-study', 'Charcoal figure study, dancer', NULL, 'Charcoal', '15 × 11 in', NULL, '/artworks/img-3689/01-main.jpeg', false, NULL, NULL, 1007),
('seated-woman-in-pink-and-grey-installed-view', 'Dana Crawford, Commission for the Crawford Hotel Lobby', NULL, 'Digital and oil', '52 × 48 × 2 in', NULL, '/artworks/seated-woman-in-pink-and-grey-installed-view/01-main.jpg', false, NULL, NULL, 1008),
('dark-floral-still-life-with-a-silhouette', 'Dark floral still life with a silhouette', NULL, 'Oil', '30 × 24 × 1 in', NULL, '/artworks/img-3689/01-main.jpeg', false, NULL, NULL, 1009),
('day-with-basquiat', 'Day with Basquiat', NULL, 'Oil', '18 × 12 × 1 in', NULL, '/artworks/img-3689/01-main.jpeg', false, NULL, NULL, 1010),
('img-3689', 'Dear Vincent, Nothing is Ever Finished', '2026', 'Embroidery', '12 × 9 × 1 in', NULL, '/artworks/img-3689/01-main.jpeg', false, NULL, NULL, 1011),
('digital-rider', 'Digital Rider', NULL, 'Oil', '28 × 28 × 1 in', NULL, '/artworks/img-3689/01-main.jpeg', false, NULL, NULL, 1012),
('lilies-in-an-urn-on-a-wooden-panel', 'Eidleweiss', NULL, 'Oil', '18 × 12 × 1 in', NULL, '/artworks/img-3689/01-main.jpeg', false, NULL, NULL, 1013),
('woman-with-a-horse-on-brown-paper', 'Even in the Daylight', NULL, 'oil', '28 × 20 × 1 in', 'This piece is part of a series around vulnerability.  After a home invasion in 2022, I dove into work about survival and recovery featuring a number of women archers.', '/artworks/img-3689/01-main.jpeg', false, NULL, NULL, 1014),
('figures-on-orange-plates-pair', 'Figures on orange plates (pair)', NULL, NULL, NULL, NULL, '/artworks/seated-woman-in-pink-and-grey-installed-view/01-main.jpg', false, NULL, NULL, 1015),
('floating-roses', 'Floating Roses', NULL, 'oil', '20 × 16 in', NULL, '/artworks/img-3689/01-main.jpeg', false, NULL, NULL, 1016),
('img-3688', 'Flower Study in Light', '2026', 'Oil', '36 × 24 × 1 in', NULL, '/artworks/img-3689/01-main.jpeg', false, NULL, NULL, 1017),
('flowers-in-a-footed-urn-with-cherries', 'Flowers in a footed urn with cherries', NULL, NULL, NULL, NULL, '/artworks/seated-woman-in-pink-and-grey-installed-view/01-main.jpeg', false, NULL, NULL, 1018),
('flowers-in-a-glass-jar-on-red', 'Flowers in a glass jar on red', NULL, NULL, NULL, NULL, '/artworks/seated-woman-in-pink-and-grey-installed-view/01-main.jpg', false, NULL, NULL, 1019),
('flowers-in-a-green-bowl', 'Flowers in a green bowl', NULL, NULL, NULL, NULL, '/artworks/img-3689/01-main.jpeg', false, NULL, NULL, 1020),
('flowers-in-a-white-jug', 'Flowers in a white jug', NULL, 'Oil', '15 × 12 in', NULL, '/artworks/img-3689/01-main.jpeg', false, NULL, NULL, 1021),
('flowers-with-colour-blocks', 'Flowers with colour blocks', NULL, NULL, NULL, NULL, '/artworks/img-3689/01-main.jpeg', false, NULL, NULL, 1022),
('francesca-at-night', 'Francesca at Night', '2026', 'Oil', '36 × 36 × 2 in', NULL, '/artworks/seated-woman-in-pink-and-grey-installed-view/01-main.jpeg', false, NULL, NULL, 1023),
('galavanting-in-guccis', 'Galavanting in Gucci''s', NULL, 'Oil', '30 × 24 × 1 in', NULL, '/artworks/img-3689/01-main.jpeg', false, NULL, NULL, 1024),
('girl-in-a-yellow-dress-with-a-dog', 'Girl in a yellow dress with a dog', NULL, NULL, NULL, NULL, '/artworks/img-3689/01-main.jpeg', false, NULL, NULL, 1025),
('green-figure-study', 'Green figure study', NULL, NULL, NULL, NULL, '/artworks/img-3689/01-main.jpeg', false, NULL, NULL, 1026),
('green-vase-on-a-red-wall', 'Green vase on a red wall', NULL, NULL, NULL, NULL, '/artworks/img-3689/01-main.jpeg', false, NULL, NULL, 1027),
('head-study-with-a-ruff', 'Head study with a ruff', NULL, NULL, NULL, NULL, '/artworks/img-3689/01-main.jpeg', false, NULL, NULL, 1028),
('figure-on-blue', 'Holding Stars', NULL, 'oil', '24 × 18 in', NULL, '/artworks/img-3689/01-main.jpeg', false, NULL, NULL, 1029),
('man-in-a-red-jacket-with-a-horse', 'Man in a red jacket with a horse', NULL, NULL, NULL, NULL, '/artworks/img-3689/01-main.jpeg', false, NULL, NULL, 1030),
('modern-cowgirl', 'Modern Cowgirl', '2026', 'Oil', '18 × 14 × 1 in', NULL, '/artworks/img-3689/01-main.jpeg', false, NULL, NULL, 1031),
('mother', 'Mother', NULL, NULL, '24 × 18 in', NULL, '/artworks/img-3689/01-main.jpeg', false, NULL, NULL, 1032),
('rider-on-a-horse-green-ground', 'Ms. Silvia Rouland', NULL, 'Digital, oil and encaustic', '30 × 30 × 2 in', NULL, '/artworks/img-3689/01-main.jpeg', false, NULL, NULL, 1033),
('odd-friends', 'Odd Friends', NULL, 'Oil and encaustic', '11 × 15 × 1 in', NULL, '/artworks/img-3689/01-main.jpeg', false, NULL, NULL, 1034),
('pink-flowers-on-a-chequered-cloth', 'Pansies on plaid', NULL, 'Digital', '24 × 18 in', NULL, '/artworks/img-3689/01-main.jpeg', false, NULL, NULL, 1035),
('piquant-poppies', 'Piquant Poppies', NULL, 'oil', '16 × 20 × 1 in', NULL, '/artworks/img-3689/01-main.jpeg', false, NULL, NULL, 1036),
('poppies-in-a-blue-vase-with-keys', 'Poppies in a blue vase with keys', NULL, NULL, NULL, NULL, '/artworks/img-3689/01-main.jpeg', false, NULL, NULL, 1037),
('poppies-with-ginori-plate', 'Poppies with Ginori Plate', '2026', 'Oil', '15 × 12 × 1 in', NULL, '/artworks/seated-woman-in-pink-and-grey-installed-view/01-main.jpeg', false, NULL, NULL, 1038),
('powerful-pansies', 'Powerful Pansies', NULL, 'Oil', '15 × 11 × 1 in', NULL, '/artworks/img-3689/01-main.jpeg', false, NULL, NULL, 1039),
('img-3697', 'Same Mood, diptych', NULL, 'Oil', '16 × 13 × 1 in', NULL, '/artworks/img-3689/01-main.jpeg', false, NULL, NULL, 1040),
('self-portrait', 'Self Portrait', NULL, 'Oil', '20 × 14 × 1 in', NULL, '/artworks/img-3689/01-main.jpeg', false, NULL, NULL, 1041),
('sunflowers-in-a-yellow-jug', 'Sunflowers in a yellow jug', NULL, 'Oil', '18 × 14 × 1 in', NULL, '/artworks/img-3689/01-main.jpeg', false, NULL, NULL, 1042),
('three-boys-photograph-and-colour-blocks', 'Three boys (photograph and colour blocks)', NULL, NULL, NULL, NULL, '/artworks/seated-woman-in-pink-and-grey-installed-view/01-main.jpg', false, NULL, NULL, 1043),
('time-with-clemente', 'Time with Clemente', NULL, 'Oil', '22 × 18 × 1 in', NULL, '/artworks/img-3689/01-main.jpeg', false, NULL, NULL, 1044),
('two-men-embracing', 'Two men embracing', NULL, NULL, NULL, NULL, '/artworks/img-3689/01-main.jpeg', false, NULL, NULL, 1045),
('woman-on-a-bench-with-crows', 'Waiting for Arlo', NULL, 'oil', '48 × 48 × 2 in', NULL, '/artworks/img-3689/01-main.jpeg', false, NULL, NULL, 1046),
('waitinf-for-starman', 'Waiting for Starman', '2025', 'Oil', '11 × 15 × 1 in', NULL, '/artworks/img-3689/01-main.jpeg', false, NULL, NULL, 1047),
('woman-in-a-blue-dress-with-blossom', 'Woman in a blue dress with blossom', NULL, NULL, NULL, NULL, '/artworks/img-3689/01-main.jpeg', false, NULL, NULL, 1048),
('woman-in-a-blue-hat-with-magnolias-painted-tray', 'Woman in a blue hat with magnolias (painted tray)', NULL, NULL, NULL, NULL, '/artworks/seated-woman-in-pink-and-grey-installed-view/01-main.jpg', false, NULL, NULL, 1049),
('woman-in-a-tall-black-hat', 'Woman in a tall black hat', NULL, NULL, NULL, NULL, '/artworks/img-3689/01-main.jpeg', false, NULL, NULL, 1050),
('woman-in-a-yellow-coat-with-a-dog', 'Woman in a yellow coat with a dog', NULL, NULL, NULL, NULL, '/artworks/seated-woman-in-pink-and-grey-installed-view/01-main.jpg', false, NULL, NULL, 1051),
('woman-in-grass-with-wildflowers', 'Woman in grass with wildflowers', NULL, NULL, NULL, NULL, '/artworks/seated-woman-in-pink-and-grey-installed-view/01-main.jpg', false, NULL, NULL, 1052);